url: 'btf-security-jekyll'
baseurl: 'https://kristenzirkler.github.com/btf-security-static'
title: 'BTF Security'
description: 'meta description'
livereload: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  solutions:
    output: true
    output_ext: .html
    permalink: /solution/:path/