url: 'btf-security-jekyll'
baseurl: 'https://kristenzirkler.github.com/btf-security-jekyll'
title: 'BTF Security'
livereload: true

plugins:
  - jekyll-postcss-v2

postcss:
  script: node_modules/.bin/postcss
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

collections:
  solutions:
    output: true
    output_ext: .html
    permalink: /solution/:path/